name: Publish Docker image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name for release versioning'
        required: true

jobs:
  set_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set version from codebase
      run: |
        VERSION=$(cat version.txt)
        echo "version=${VERSION}" >> $GITHUB_ENV

  publish:
    needs: set_version
    if: startsWith(github.event.inputs.branch_name, 'release-')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/your-organization/your-repository/jmeter-base:${{ env.version }}
